language: node_js
sudo: false
node_js:
- '8'
branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GIT_TOKEN  # Set in travis-ci.org dashboard
  local_dir: ./dist
  on:
    branch: master